networks:
  expense: {}
# docker volume create mysql
volumes:
  mysql:
services:

# docker run -d --name backend --network expense  backend:1.0.0 
  backend:
    image: backend:1.0.0
    command: sh -c "sleep 5 && node /opt/backend/index.js"
    networks:
    - expense
    container_name: backend
    depends_on:
    - mysql

# docker run -d --name mysql --network expense -v mysql:/var/lib/mysql mysql:1.0.0 
  mysql:
    image: mysql:1.0.0
    networks:
    - expense
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql

# docker run -d --name frontend --network expense -p 80:80 frontend:1.0.0
  frontend:
    image: frontend:1.0.0
    networks:
    - expense
    container_name: frontend
    ports:
    - 00:80
    depends_on:
    - backend
    

